### PR TITLE
chore: move graph animations to UI thread

### PR DESCRIPTION
**Pull request by Nodonisko**
https://github.com/Shopify/react-native-skia/pull/1341 made possible to use Reanimated Values directly, is now possible to run animations fully on UI thread (Skia runs them only partially on UI thread).

- Gesture is now super fast and don't lag behind finger if you swipe really really fast
- Sadly onPointSelected callback still can lag behind

TODO:
- [x] Update example app RN version and test it there (now it's tested only in my app)

### CODE REVIEW

**Comment by chrispader** [comment]
LGTM! 🚀 Thanks for a great PR. This is a really good performance improvement

Needed to bump `react-native` version, but this PR was a good opportunity, as we were way behind the current version.

**Comment by chrispader** [comment]
I still need to fix the android build of the example app, but the rest works fine!

**Comment by Nodonisko** [comment]
@chrispader please also bump Skia to latest version because there was bug that randomly crashed app when it was used in combination with Reanimated https://github.com/Shopify/react-native-skia/issues/1517

**Comment by ArtKullashi** [comment]
I hope this also fixes a weird bug with the graph not animating between data changes. I was going create an issue but will wait for this update first.

**Comment by chrispader** [comment]
Fixed the build for android, will merge this now.

Thanks to everybody who contributed on this change! 🚀🥳 @Nodonisko @lewiscasewell

**Comment by wcandillon** [comment]
very nice. We use similar code on our apps and it seems to work great!

**Comment by Nodonisko** [comment]
@wcandillon The animation of graph line it's still done using Skia animations because I am not sure how to animate SkPath using reanimated. Can you hint me how to do that?

**Comment by wcandillon** [comment]
yes this would be the source of truth at the moment: https://github.com/Shopify/react-native-skia/blob/main/example/src/Examples/Wallet/Wallet.tsx#L34

**Pull request merged**
