### PR TITLE
fix: Remove incorrect delta from pixel factor calculation

### PR DESCRIPTION
**Pull request by thomas-coldwell**
This PR fixes an issue identified where some later dates in the points data would cause NaNs in the cubic path calculation. Once I removed the delta value for the `pixelFactorX` calculation the graph rendered correctly with a valid path.

I'm not fully sure I understand why this fixes it so would be great if you could shed some light here @chrispader and make sure I'm not breaking something else with this change 😄

### CODE REVIEW

**Comment by chrispader** [comment]
I made some improvements to how all of the `createGraphPath()` logic is working in #52 , but i don't know if this exactly fixes your problem. 

I tested your changes with the latest main branch and it seems to be very laggy for me. Not sure yet, what's causing this.

https://user-images.githubusercontent.com/20173411/212394582-1ad55cb7-bf0f-4002-aca8-52d360614315.mp4

**Comment by chrispader** [comment]
Both the pan gesture as well as initial rendering is very laggy atm, investigating this now. @thomas-coldwell would my mind trying the current changes in main with your project. Maybe the issue is fixed already

**Comment by thomas-coldwell** [comment]
Hey @chrispader I've tried the latest changes on `main`, but this still creates `NaN`s in the cubic path calculation and thus causes no graph to be rendered:

**Comment by thomas-coldwell** [comment]
This latest change should fix the `drawingFactor` calculation. Prior to this change it was creating hundreds of points in-between data points hence the lag when scrubbing over the graph 😄

**Review by chrispader — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
