### PR TITLE
hot swap skia useValue and runSpring hooks with standard reanimated ones

### PR DESCRIPTION
**Pull request by daxaxelrod**
Need a second pair of eyes here. Got everything to compile but having trouble when testing locally. I git cloned the repo and then used `npm link` to install it locally in another project as a testing ground (also modified metro, thats project references work just fine). 

I keep getting a _measure is undefined error which tells me that the babel worklet plugin is not working. Also when I comment out props.animated in src/LineGraph.tsx to just render the static line component, it throws a couple of react errors which I know shouldnt be happening: Invalid hook call, `Hooks can only be called in the body of a function` and cannot read property 'useState' of null.

Any ideas? SO and gpt came up dry. How did you test the lib locally @mrousavy

### CODE REVIEW

**Comment by mrousavy** [comment]
Hey, thanks for your PR!

To test it locally just run the `example/` app here.

**Comment by daxaxelrod** [comment]
Thanks, not working quite right yet, will do more testing over the weekend

**Comment by vovacodes** [comment]
Any luck with fixing the example? Running into this in project too :(

**Comment by dsshard** [comment]
Hello! Are there any updates on this PR?

**Comment by gabimoncha** [comment]
@mrousavy this PR is not needed anymore since the migration was done

**Comment by mrousavy** [comment]
yup 👍

**Comment by mrousavy** [comment]
released in latest version on npm

**Pull request closed without merging**
